nome = input("Digite o seu nome: ")
dia = input("Digite o dia que você nasceu: ")
mes = input("Digite o mês que você nasceu: ")
ano = input("Digite o ano que você nasceu: ")
print("Seja muito bem vinde {}! Uhu. A data do seu aniversário é {}/{}/{}.".format(nome, dia, mes, ano))
